# Dependabot Configuration
# Automatically checks for dependency updates and creates PRs
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # NPM dependencies (Frontend & Backend)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 10
    reviewers:
      - "tailoredcaresolutions/maintainers"
    assignees:
      - "tailoredcaresolutions/maintainers"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Security updates get priority
    allow:
      - dependency-type: "all"
    # Ignore major version updates (require manual review)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Backend NPM dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 5
    reviewers:
      - "tailoredcaresolutions/maintainers"
    labels:
      - "dependencies"
      - "backend"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      backend-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 5
    reviewers:
      - "tailoredcaresolutions/maintainers"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"
