blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/tailoredcaresolutions/2424/discussions
    about: Ask questions, share ideas, or discuss the project
  - name: 📚 Documentation
    url: https://github.com/tailoredcaresolutions/2424/blob/main/README.md
    about: Read the documentation and guides
  - name: 🔒 Security Advisory (Private)
    url: https://github.com/tailoredcaresolutions/2424/security/advisories/new
    about: Report sensitive security vulnerabilities privately
